### ISSUE TITLE
sysfs documentation

### ISSUE THREAD

**Issue by kiddjmadd** [malokhvii-eduard/lkmod-bme280#28]
Minor suggestion on documentation. For my beaglebone blue, the temp, humidity and pressure readings were accessible under /sys/class/bme280 vs. /sys/bme280. Feel free to close the issue, I just wanted to put this out there in case someone else uses this module for an SBC other than Raspberry Pi. Thanks for the great module!

**Comment by malokhvii-eduard** [comment]
@kiddjmadd Thank you for your suggestion.
